### ISSUE TITLE
[Suggestion] More Shorthand Terms

### ISSUE THREAD

**Issue by CodeNinja212** [andr30z/fgc-combo-companion#101]
Just a few more terms I wish are also implemented into the combo translator.

- HD - HEAT-DASH
- WBL! - WALL-BLAST
- WBO! - WALL-BOUND
- FBO! - FLOOR-BLAST

**Comment by andr30z** [comment]
Thanks for the suggestions.

I'm not having much time right now. Maybe next week I'll take some time to add these terms

**Comment by andr30z** [comment]
https://github.com/andr30z/fgc-combo-companion/pull/102
